# See COPYING for license.

sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -f Dockerfile.travis -t primecoin .

script:
  - docker run primecoin bin/sh -c "cd src && make"
  - docker run primecoin bin/sh -c "cd src && make test"
  - docker run primecoin bin/sh -c "qmake && make"
  - docker run primecoin bin/sh -c "qmake PRIMECOIN_QT_TEST=1 && make && ./primecoin-qt_test"
