# See COPYING for license.

sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t primecoin .

script:
  - docker run primecoin bin/sh -c "cd src/server && make"
  - docker run primecoin bin/sh -c "cd src/server && make test"
  - docker run primecoin bin/sh -c "cd src/wallet && qmake-qt4 && make"
  - docker run primecoin bin/sh -c "cd src/wallet && qmake-qt4 PRIMECOIN_QT_TEST=1 && make && ./primecoin-qt_test"
