sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t primecoin-test .

script:
  - docker run primecoin-test bin/sh -c "qmake BITCOIN_QT_TEST=1 && make && ./bitcoin-qt_test"
  - docker run primecoin-test bin/sh -c "cd src && make test"
